# Build and publish to npm whenever a new release is made
name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: |
          VERSION=$GITHUB_REF_NAME
          # Set the version in package.json
          npm version $VERSION --no-git-tag-version
          npm publish
          --access public
          --tag ${{ github.event.release.prerelease && 'next' || 'latest' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
